from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BASE_DIR / "data"
MEDIA_DIR = BASE_DIR / "media"
AUDIO_DIR = MEDIA_DIR / "audio"
TRANSCRIPT_DIR = DATA_DIR / "transcripts"
EVW_EVENTS_FILE = DATA_DIR / "events" / "east_vs_west_events.json"
KOTT_EVENTS_FILE = DATA_DIR / "events" / "kott_events.json"
YOUTUBE_DATA = DATA_DIR / "youtube" / "youtube_completed_lives.json"
ATHLETE_EXAMPLE_FILE = DATA_DIR / "athlete_example.json"
ATHLETE_COUNTRY_FILE = DATA_DIR / "athlete_country.json"
UNIQUE_ATHLETES_FILE = DATA_DIR / "unique_athletes.json"
UNIQUE_ATHLETES_WITH_DATA_FILE = DATA_DIR / "unique_athletes_with_data.json"
TRAVEL_EFFECT_FILE = DATA_DIR / "travel_effect_analysis.json"
VALUEABLE_MATCHES_FILE = DATA_DIR / "valuable_comparisons.json"
UPDATED_TRAINING_FEATURES_WITH_TRAVEL_STATS = DATA_DIR / "training_features_with_travel_stats.csv"
GOLDSARM_DIR = DATA_DIR / "goldsarm"
ATHLETES_DIR = DATA_DIR / "athletes"
PREDICTIONS_DIR = DATA_DIR / "predictions"
HF_TOKEN = "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"
SHALLOWSEEK_APIK="sk-0cc54fb71e7c4b4381d5fafad5e7d1f5"
YOUTUBE_API_KEY="AIzaSyBkSNYJxSMBlqLkZXTDNZ1dAFyABuSKUwE"
YOUTUBE_API_KEY2="AIzaSyDpRnfQ-QX1tdkdcqen7E3YxWDPEA2kba0"
API_URL="https://api.deepseek.com/v1/chat/completions"
OPENAI_API_KEY = "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"
