// Autogenerated athletes and countries data

export const athletes = [
  {
    "name": "Abdulmanaf Tuzuyev",
    "country": "Kazakhstan",
    "photo": "goldsarm/abdulmanaf-tuzuyev.jpg",
    "gender": "male"
  },
  {
    "name": "Adam Wawrzynski",
    "country": "United States Of America",
    "photo": "goldsarm/adam-wawrzynski.png",
    "gender": "male"
  },
  {
    "name": "Ahmet Yenerer",
    "country": "Turkey",
    "photo": "goldsarm/ahmet-yenerer.jpg",
    "gender": "male"
  },
  {
    "name": "Aleksandr Beziazykov",
    "country": "Russia",
    "photo": "goldsarm/aleksandr-beziazykov.jpg",
    "gender": "male"
  },
  {
    "name": "Aleksandra Ozerova",
    "country": "Russia",
    "photo": "goldsarm/aleksandra-ozerova.jpg",
    "gender": "female"
  },
  {
    "name": "Alex Kurdecha",
    "country": "Poland",
    "photo": "goldsarm/alex-kurdecha.jpg",
    "gender": "male"
  },
  {
    "name": "Alizhan Muratov",
    "country": "Kazakhstan",
    "photo": "goldsarm/alizhan-muratov.jpg",
    "gender": "male"
  },
  {
    "name": "Allen Ford",
    "country": "Canada",
    "photo": "goldsarm/allen-ford.png",
    "gender": "male"
  },
  {
    "name": "Andrei Chipreanov",
    "country": "Moldova",
    "photo": "goldsarm/andrei-chipreanov.jpg",
    "gender": "male"
  },
  {
    "name": "Andrei Sharkevich",
    "country": "Russia",
    "photo": "goldsarm/andrei-sharkevich.jpg",
    "gender": "male"
  },
  {
    "name": "Angie Rose",
    "country": "Canada",
    "photo": "goldsarm/angie-rose.jpg",
    "gender": "female"
  },
  {
    "name": "Anna Gronlund",
    "country": "Sweden",
    "photo": "goldsarm/anna-gronlund.jpg",
    "gender": "female"
  },
  {
    "name": "Arif Ertem",
    "country": "Turkey",
    "photo": "goldsarm/arif-ertem.jpg",
    "gender": "male"
  },
  {
    "name": "Arsen Khachatryan",
    "country": "Russia",
    "photo": "goldsarm/arsen-khachatryan.png",
    "gender": "male"
  },
  {
    "name": "Artem Taranenko",
    "country": "United States Of America",
    "photo": "goldsarm/artem-taranenko.jpg",
    "gender": "male"
  },
  {
    "name": "Artem Taynov",
    "country": "Russia",
    "photo": "goldsarm/artem-taynov.jpg",
    "gender": "male"
  },
  {
    "name": "Artur Makarov",
    "country": "Russia",
    "photo": "goldsarm/arthur-makarov.jpg",
    "gender": "male"
  },
  {
    "name": "Artyom Morozov",
    "country": "Kazakhstan",
    "photo": "goldsarm/artyom-morozov.jpg",
    "gender": "male"
  },
  {
    "name": "Auden Larratt",
    "country": "Canada",
    "photo": "goldsarm/auden-larratt.png",
    "gender": "male"
  },
  {
    "name": "Avtandil Tutberidze",
    "country": "Georgia",
    "photo": "goldsarm/avtandil-tutberidze.jpg",
    "gender": "male"
  },
  {
    "name": "Ayane Takenaka",
    "country": "Japan",
    "photo": "goldsarm/ayane-takenaka.png",
    "gender": "female"
  },
  {
    "name": "Aymeric Pradines",
    "country": "France",
    "photo": "goldsarm/aymeric-pradine.jpg",
    "gender": "male"
  },
  {
    "name": "Azat Srapyan",
    "country": "Armenia",
    "photo": "goldsarm/azat-srapyan.jpg",
    "gender": "male"
  },
  {
    "name": "Bacho Saginashvili",
    "country": "Georgia",
    "photo": "goldsarm/bacho-saginashvili.jpg",
    "gender": "male"
  },
  {
    "name": "Barbora Bajciova",
    "country": "Slovakia",
    "photo": "goldsarm/barbora-bajciova.jpg",
    "gender": "female"
  },
  {
    "name": "Beket Aitbek",
    "country": "Kazakhstan",
    "photo": "goldsarm/aitbek-beket.jpg",
    "gender": "male"
  },
  {
    "name": "Bela Plieva",
    "country": "Russia",
    "photo": "goldsarm/bela-plieva.png",
    "gender": "male"
  },
  {
    "name": "Betkili Oniani",
    "country": "Georgia",
    "photo": "goldsarm/betkili-oniani.jpg",
    "gender": "male"
  },
  {
    "name": "Bozhidar Simeonov",
    "country": "Bulgaria",
    "photo": "goldsarm/bozhidar-simeonov.jpg",
    "gender": "male"
  },
  {
    "name": "Brad Grundy",
    "country": "United States Of America",
    "photo": "goldsarm/brad-grundy.jpg",
    "gender": "male"
  },
  {
    "name": "Brandon Allen",
    "country": "United States Of America",
    "photo": "goldsarm/brandon-allen.jpg",
    "gender": "male"
  },
  {
    "name": "Brandon Ellsessor",
    "country": "United States Of America",
    "photo": "goldsarm/brandon-ellessor.jpg",
    "gender": "male"
  },
  {
    "name": "Brian Shaw",
    "country": "United States Of America",
    "photo": "goldsarm/brian-shaw.png",
    "gender": "male"
  },
  {
    "name": "Brigitta Ivanfi",
    "country": "Hungary",
    "photo": "goldsarm/brigitta-ivanfi.png",
    "gender": "male"
  },
  {
    "name": "Carolina Pettersson",
    "country": "Sweden",
    "photo": "goldsarm/carolina-pettersson.jpg",
    "gender": "male"
  },
  {
    "name": "Chance Shaw",
    "country": "United States Of America",
    "photo": "goldsarm/chance-shaw.jpg",
    "gender": "male"
  },
  {
    "name": "Cobra Rhodes",
    "country": "United States Of America",
    "photo": "goldsarm/cobra-rhodes.jpg",
    "gender": "male"
  },
  {
    "name": "Cody Wood",
    "country": "United States Of America",
    "photo": "goldsarm/cody-wood.png",
    "gender": "male"
  },
  {
    "name": "Corey Miller",
    "country": "United States Of America",
    "photo": "goldsarm/corey-miller.jpg",
    "gender": "male"
  },
  {
    "name": "Corey West",
    "country": "United States Of America",
    "photo": "goldsarm/corey-west.jpg",
    "gender": "male"
  },
  {
    "name": "Craig Tullier",
    "country": "United States Of America",
    "photo": "goldsarm/craig-tullier.png",
    "gender": "male"
  },
  {
    "name": "Curtis Cameron",
    "country": "Canada",
    "photo": "goldsarm/curtis-cameron.jpg",
    "gender": "male"
  },
  {
    "name": "Daniel Procopciuc",
    "country": "Moldova",
    "photo": "goldsarm/daniel-procopciuc.jpg",
    "gender": "male"
  },
  {
    "name": "Danil Ustinov",
    "country": "Kazakhstan",
    "photo": "goldsarm/daniel-ustinov.jpg",
    "gender": "male"
  },
  {
    "name": "Dave Chaffee",
    "country": "United States Of America",
    "photo": "goldsarm/dave-chaffee.jpg",
    "gender": "male"
  },
  {
    "name": "David Dadikyan",
    "country": "Armenia",
    "photo": "goldsarm/david-dadikyan.jpg",
    "gender": "male"
  },
  {
    "name": "Davit Arabuli",
    "country": "Georgia",
    "photo": "goldsarm/davit-arabuli.jpg",
    "gender": "male"
  },
  {
    "name": "Davit Samushia",
    "country": "Georgia",
    "photo": "goldsarm/davit-samushia.jpg",
    "gender": "male"
  },
  {
    "name": "Denis Cyplenkov",
    "country": "Russia",
    "photo": "goldsarm/denis--cyplenkov.jpg",
    "gender": "male"
  },
  {
    "name": "Derek Smith",
    "country": "United States Of America",
    "photo": "goldsarm/derek-smith.jpg",
    "gender": "male"
  },
  {
    "name": "Devon Larratt",
    "country": "Canada",
    "photo": "goldsarm/devon-larratt.jpg",
    "gender": "male"
  },
  {
    "name": "Dimitrina Petrova",
    "country": "Bulgaria",
    "photo": "goldsarm/dimitrina-petrova.jpg",
    "gender": "female"
  },
  {
    "name": "Doug Erlich",
    "country": "United States",
    "photo": "goldsarm/doug-erlich.jpg",
    "gender": "male"
  },
  {
    "name": "Dustin Hyatt",
    "country": "USA",
    "photo": "goldsarm/dustin-hyatt.jpg",
    "gender": "male"
  },
  {
    "name": "Eddie Hall",
    "country": "United Kingdom",
    "photo": "goldsarm/eddie-hall.png",
    "gender": "male"
  },
  {
    "name": "Efe Komek",
    "country": "Turkey",
    "photo": "goldsarm/efe-komek.jpg",
    "gender": "male"
  },
  {
    "name": "Egle Vaitkute",
    "country": "Lithuania",
    "photo": "goldsarm/egle-vaitkute.jpg",
    "gender": "female"
  },
  {
    "name": "Ekaterina Nikisheva",
    "country": "Russia",
    "photo": "goldsarm/ekaterina-nikisheva.jpg",
    "gender": "male"
  },
  {
    "name": "Elin Janeheim",
    "country": "Sweden",
    "photo": "goldsarm/elin-janeheim.png",
    "gender": "male"
  },
  {
    "name": "Elizabeth Mocek",
    "country": "United States Of America",
    "photo": "goldsarm/elizabeth-rae-mocek.jpg",
    "gender": "female"
  },
  {
    "name": "Emil Amirshadyan",
    "country": "Armenia",
    "photo": "goldsarm/emil-amirshadyan.jpg",
    "gender": "male"
  },
  {
    "name": "Engin Terzi",
    "country": "Turkey",
    "photo": "goldsarm/engin-terzi.jpg",
    "gender": "male"
  },
  {
    "name": "Erkan Damar",
    "country": "Turkey",
    "photo": "goldsarm/erkan-damar.png",
    "gender": "male"
  },
  {
    "name": "Ermes Gasparini",
    "country": "Italy",
    "photo": "goldsarm/ermes-gasparini.png",
    "gender": "male"
  },
  {
    "name": "Esra Kiraz",
    "country": "Turkey",
    "photo": "goldsarm/esra-kiraz.jpg",
    "gender": "male"
  },
  {
    "name": "Evgeny Prudnik",
    "country": "Ukraine",
    "photo": "goldsarm/evgeny-prudnik.jpg",
    "gender": "male"
  },
  {
    "name": "Ferit Osmanli",
    "country": "Turkey",
    "photo": "goldsarm/ferit-osmanli.jpg",
    "gender": "male"
  },
  {
    "name": "Fia Reisek",
    "country": "Sweden",
    "photo": "goldsarm/fia-reisek.png",
    "gender": "male"
  },
  {
    "name": "Frank Lamparelli",
    "country": "Italy",
    "photo": "goldsarm/frank-lamparelli.jpg",
    "gender": "male"
  },
  {
    "name": "Gabor Botta Dukat",
    "country": "Hungary",
    "photo": "goldsarm/gabor-botta-dukat.png",
    "gender": "male"
  },
  {
    "name": "Gabriela Vasconcelos",
    "country": "Brazil",
    "photo": "goldsarm/gabi-vasconcelos.jpg",
    "gender": "female"
  },
  {
    "name": "Genadi Kvikvinia",
    "country": "Georgia",
    "photo": "goldsarm/genadi-kvikvinia.png",
    "gender": "male"
  },
  {
    "name": "Georgi Tsvetkov",
    "country": "Bulgaria",
    "photo": "goldsarm/georgi-tsvetkov.png",
    "gender": "male"
  },
  {
    "name": "Georgii Dzeranov",
    "country": "Kazakhstan",
    "photo": "goldsarm/georgii-dzeranov.jpg",
    "gender": "male"
  },
  {
    "name": "Georgy Tautiev",
    "country": "Russia",
    "photo": "goldsarm/georgy-tautiev.jpg",
    "gender": "male"
  },
  {
    "name": "Haydar Gildil",
    "country": "Turkey",
    "photo": "goldsarm/haydar-gildil.jpg",
    "gender": "male"
  },
  {
    "name": "Herman Stevens",
    "country": "United States Of America",
    "photo": "goldsarm/herman-stevens.jpg",
    "gender": "male"
  },
  {
    "name": "Hristo Delidzhakov",
    "country": "Bulgaria",
    "photo": "goldsarm/hristo-delidzhakov.jpg",
    "gender": "male"
  },
  {
    "name": "Hunter Noffz",
    "country": "United States Of America",
    "photo": "goldsarm/hunter-noffz.jpg",
    "gender": "male"
  },
  {
    "name": "Ibragim Sagov",
    "country": "Russia",
    "photo": "goldsarm/ibrahim-sagov.jpg",
    "gender": "male"
  },
  {
    "name": "Irakli Zirakashvili",
    "country": "Georgia",
    "photo": "goldsarm/irakli-zirakashvili.jpg",
    "gender": "male"
  },
  {
    "name": "Irina Drieva",
    "country": "Russia",
    "photo": "goldsarm/irina-drieva.png",
    "gender": "female"
  },
  {
    "name": "Irina Gladkaya",
    "country": "Russia",
    "photo": "goldsarm/irina-gladkaya.jpg",
    "gender": "female"
  },
  {
    "name": "Ivan Matyushenko",
    "country": "Russia",
    "photo": "goldsarm/ivan-matyushenko.jpg",
    "gender": "male"
  },
  {
    "name": "Ivan Portela",
    "country": "Spain",
    "photo": "goldsarm/ivan-portela.png",
    "gender": "male"
  },
  {
    "name": "Janis Amolins",
    "country": "Latvia",
    "photo": "goldsarm/janis-amolins.jpg",
    "gender": "male"
  },
  {
    "name": "Jerry Cadorette",
    "country": "United States Of America",
    "photo": "goldsarm/jerry-cadorette.png",
    "gender": "male"
  },
  {
    "name": "Jocelyne Brisson",
    "country": "Canada",
    "photo": "goldsarm/jocelyne-brisson.png",
    "gender": "male"
  },
  {
    "name": "John Brzenk",
    "country": "United States Of America",
    "photo": "goldsarm/john-brzenk.jpg",
    "gender": "male"
  },
  {
    "name": "John Therrien",
    "country": "Canada",
    "photo": "goldsarm/john-therrien.png",
    "gender": "male"
  },
  {
    "name": "Jonathan Breda",
    "country": "United States Of America",
    "photo": "goldsarm/jonathon-breda.jpg",
    "gender": "male"
  },
  {
    "name": "Joseph Meranto",
    "country": "United States Of America",
    "photo": "goldsarm/joseph-meranto.jpg",
    "gender": "male"
  },
  {
    "name": "Joshua Grant",
    "country": "Canada",
    "photo": "goldsarm/joshua-grant.png",
    "gender": "male"
  },
  {
    "name": "Justin Bishop",
    "country": "United States Of America",
    "photo": "goldsarm/justin-bishop.jpg",
    "gender": "male"
  },
  {
    "name": "Kacper Sinica",
    "country": "Poland",
    "photo": "goldsarm/kacper-sinica.jpg",
    "gender": "male"
  },
  {
    "name": "Kamil Jablonski",
    "country": "Poland",
    "photo": "goldsarm/kamil-jablonski.jpg",
    "gender": "male"
  },
  {
    "name": "Kevin Palko",
    "country": "United States Of America",
    "photo": "goldsarm/kevin-palko.png",
    "gender": "male"
  },
  {
    "name": "Khadzimurat Zoloev",
    "country": "Russia",
    "photo": "goldsarm/khadzimurat-zoloev.jpg",
    "gender": "male"
  },
  {
    "name": "Khaled Jashell",
    "country": "Cameroon",
    "photo": "goldsarm/khaled-jashell.jpg",
    "gender": "male"
  },
  {
    "name": "Kody Merritt",
    "country": "United States Of America",
    "photo": "goldsarm/kody-merritt.png",
    "gender": "male"
  },
  {
    "name": "Korean Hulk",
    "country": "South Korea",
    "photo": "goldsarm/korean-hulk.png",
    "gender": "male"
  },
  {
    "name": "Krasimir Kostadinov",
    "country": "Bulgaria",
    "photo": "goldsarm/krasimir-kostadinov.png",
    "gender": "male"
  },
  {
    "name": "Kydyrgali Ongarbaev",
    "country": "Kazakhstan",
    "photo": "goldsarm/kydyrgali-ongarbaev.jpg",
    "gender": "male"
  },
  {
    "name": "Kyle Hutchison",
    "country": "United Kingdom",
    "photo": "goldsarm/kyle-hutchison.jpg",
    "gender": "male"
  },
  {
    "name": "Lachlan Adair",
    "country": "Australia",
    "photo": "goldsarm/lachlan-adair.jpg",
    "gender": "male"
  },
  {
    "name": "Larry Wheels",
    "country": "United States Of America",
    "photo": "goldsarm/larry-wheels.jpg",
    "gender": "male"
  },
  {
    "name": "Lars Rorbakken",
    "country": "Norway",
    "photo": "goldsarm/lars-rorbakken.jpg",
    "gender": "male"
  },
  {
    "name": "Leonidas Arkona",
    "country": "Germany",
    "photo": "goldsarm/leonidas-arkona.jpg",
    "gender": "male"
  },
  {
    "name": "Levan Saginashvili",
    "country": "Georgia",
    "photo": "goldsarm/levan-saginashvili.jpg",
    "gender": "male"
  },
  {
    "name": "Maateiwarangi Heta-Morris",
    "country": "New Zealand",
    "photo": "goldsarm/maateiwarangi-heta-morris.jpg",
    "gender": "male"
  },
  {
    "name": "Malin Bergstrom",
    "country": "Sweden",
    "photo": "goldsarm/malin-bergstorm.jpg",
    "gender": "male"
  },
  {
    "name": "Marcio Barboza",
    "country": "Brazil",
    "photo": "goldsarm/marcio-barboza.jpg",
    "gender": "male"
  },
  {
    "name": "Matt Mask",
    "country": "Canada",
    "photo": "goldsarm/matt-mask.jpg",
    "gender": "male"
  },
  {
    "name": "Mazahir Saidu",
    "country": "India",
    "photo": "goldsarm/mazahir-saidu.jpg",
    "gender": "male"
  },
  {
    "name": "Mehdi Abvolvand",
    "country": "Iran (Islamic Republic of)",
    "photo": "goldsarm/mehdi-abdolvand.jpg",
    "gender": "male"
  },
  {
    "name": "Michael Todd",
    "country": "United States Of America",
    "photo": "goldsarm/michael-todd.jpg",
    "gender": "male"
  },
  {
    "name": "Mindaugas Tarasaitis",
    "country": "Lithuania",
    "photo": "goldsarm/mindaugas-tarasaitis.jpg",
    "gender": "male"
  },
  {
    "name": "Nedalin Hristov",
    "country": "Bulgaria",
    "photo": "goldsarm/nedalin-hristov.jpg",
    "gender": "male"
  },
  {
    "name": "Nisa Camanan",
    "country": "Turkey",
    "photo": "goldsarm/nisa-camadan.jpg",
    "gender": "male"
  },
  {
    "name": "Nugo Chikadze",
    "country": "Georgia",
    "photo": "goldsarm/nugo-chikadze.jpg",
    "gender": "male"
  },
  {
    "name": "Nugzari Chikadze",
    "country": "Georgia",
    "photo": "goldsarm/nugzari-chikadze.jpg",
    "gender": "male"
  },
  {
    "name": "Nurdalet Aidarkhan",
    "country": "Kazakhstan",
    "photo": "goldsarm/nurdalet-aidarkhan.jpg",
    "gender": "male"
  },
  {
    "name": "Oguzhan Kocak",
    "country": "Turkey",
    "photo": "goldsarm/oguzhan-kocak.jpg",
    "gender": "male"
  },
  {
    "name": "Oleg Cherkasov",
    "country": "Russia",
    "photo": "goldsarm/oleg-chersakov.jpg",
    "gender": "male"
  },
  {
    "name": "Oleg Petrenko",
    "country": "Ukraine",
    "photo": "goldsarm/oleg-petrenko.jpg",
    "gender": "male"
  },
  {
    "name": "Oleg Zhokh",
    "country": "Ukraine",
    "photo": "goldsarm/oleg-zhokh.jpg",
    "gender": "male"
  },
  {
    "name": "Olga Terpelova",
    "country": "Russia",
    "photo": "goldsarm/olga-terpelova.jpg",
    "gender": "male"
  },
  {
    "name": "Omer Kozakoglu",
    "country": "Turkey",
    "photo": "goldsarm/omer-kozakoglu.jpg",
    "gender": "male"
  },
  {
    "name": "Paul Linn",
    "country": "United States Of America",
    "photo": "goldsarm/paul-linn.jpg",
    "gender": "male"
  },
  {
    "name": "Paul Talbott",
    "country": "United States Of America",
    "photo": "goldsarm/paul-talbott.jpg",
    "gender": "male"
  },
  {
    "name": "Pavlo Derbedyenyev",
    "country": "Ukraine",
    "photo": "goldsarm/pavlo-derbedyenyev.jpg",
    "gender": "male"
  },
  {
    "name": "Petro Marharint",
    "country": "Ukraine",
    "photo": "goldsarm/petro-marharint.jpg",
    "gender": "male"
  },
  {
    "name": "Raimonds Liepins",
    "country": "Latvia",
    "photo": "goldsarm/raimonds-liepins.jpg",
    "gender": "male"
  },
  {
    "name": "Ramzi Tayba",
    "country": "Qatar",
    "photo": "goldsarm/ramzi-tayba.jpg",
    "gender": "male"
  },
  {
    "name": "Rebeka Martinkovicova",
    "country": "Slovakia",
    "photo": "goldsarm/rebeka-martinkovicova.jpg",
    "gender": "male"
  },
  {
    "name": "Revaz Lutidze",
    "country": "Georgia",
    "photo": "goldsarm/revaz-lutidze.jpg",
    "gender": "male"
  },
  {
    "name": "Riekerd Bornman",
    "country": "South Africa",
    "photo": "goldsarm/riekerd-bornman.png",
    "gender": "male"
  },
  {
    "name": "Rino Masic",
    "country": "Croatia",
    "photo": "goldsarm/rino-masic.jpg",
    "gender": "male"
  },
  {
    "name": "Rob Vigeant Jr.",
    "country": "United States Of America",
    "photo": "goldsarm/rob-vigeant-jr.jpg",
    "gender": "male"
  },
  {
    "name": "Robbie Karstendiek",
    "country": "United States Of America",
    "photo": "goldsarm/robbie-karstendiek.jpg",
    "gender": "male"
  },
  {
    "name": "Robbie Topie",
    "country": "United States Of America",
    "photo": "goldsarm/robbie-topie.jpg",
    "gender": "male"
  },
  {
    "name": "Robert Baxter",
    "country": "United States Of America",
    "photo": "goldsarm/robert-baxter.jpg",
    "gender": "male"
  },
  {
    "name": "Ron Bath",
    "country": "United States Of America",
    "photo": "goldsarm/ron-bath.jpg",
    "gender": "male"
  },
  {
    "name": "Rosa Acosta (Boltadano)",
    "country": "Dominican Republic",
    "photo": "goldsarm/rosa-acosta-(boltadano).jpg",
    "gender": "male"
  },
  {
    "name": "Ruslan Babaiev",
    "country": "Ukraine",
    "photo": "goldsarm/ruslan-babayev.jpg",
    "gender": "male"
  },
  {
    "name": "Rustam Babayev",
    "country": "Ukraine",
    "photo": "goldsarm/rustam-babayev.jpg",
    "gender": "male"
  },
  {
    "name": "Ryan Belanger",
    "country": "Canada",
    "photo": "goldsarm/ryan-belanger.png",
    "gender": "male"
  },
  {
    "name": "Ryan Bowen",
    "country": "Australia",
    "photo": "goldsarm/ryan-bowen.jpg",
    "gender": "male"
  },
  {
    "name": "Sabin Badulescu",
    "country": "Romania",
    "photo": "goldsarm/sabin-badulescu.jpg",
    "gender": "male"
  },
  {
    "name": "Sahip Caglar",
    "country": "Turkey",
    "photo": "goldsarm/sahip-caglar.jpg",
    "gender": "male"
  },
  {
    "name": "Sandris Sedis",
    "country": "Latvia",
    "photo": "goldsarm/sandris-sedis.jpg",
    "gender": "male"
  },
  {
    "name": "Sarah Backman",
    "country": "United States Of America",
    "photo": "goldsarm/sarah-backman.png",
    "gender": "male"
  },
  {
    "name": "Sarah Collins",
    "country": "United States Of America",
    "photo": "goldsarm/sarah-collins.jpg",
    "gender": "male"
  },
  {
    "name": "Sasho Andreev",
    "country": "Bulgaria",
    "photo": "goldsarm/sasho-andreev.jpg",
    "gender": "male"
  },
  {
    "name": "Serhii Kalinichenko",
    "country": "Ukraine",
    "photo": "goldsarm/sergei-kalinichenko.jpg",
    "gender": "male"
  },
  {
    "name": "Stoyan Golemanov",
    "country": "Bulgaria",
    "photo": "goldsarm/stoyan-golemanov.jpg",
    "gender": "male"
  },
  {
    "name": "Talgat Aktaev",
    "country": "Kazakhstan",
    "photo": "goldsarm/talgat-aktaev.jpg",
    "gender": "male"
  },
  {
    "name": "Terence Opperman",
    "country": "South Africa",
    "photo": "goldsarm/terence-opperman.jpg",
    "gender": "male"
  },
  {
    "name": "Thomas Manghi",
    "country": "Italy",
    "photo": "goldsarm/thomas-manghi.jpg",
    "gender": "male"
  },
  {
    "name": "Tobias Sporrong",
    "country": "Sweden",
    "photo": "goldsarm/tobias-sporrong.jpg",
    "gender": "male"
  },
  {
    "name": "Todd Hutchings",
    "country": "United States Of America",
    "photo": "goldsarm/todd-hutchings.jpg",
    "gender": "male"
  },
  {
    "name": "Tom Holland",
    "country": "United Kingdom",
    "photo": "goldsarm/tom-holland.jpg",
    "gender": "male"
  },
  {
    "name": "Tom Rozits",
    "country": "Latvia",
    "photo": "goldsarm/toms-rozits.jpg",
    "gender": "male"
  },
  {
    "name": "Toms Rozits",
    "country": "Latvia",
    "photo": "goldsarm/toms-rozits.jpg",
    "gender": "male"
  },
  {
    "name": "Tony Kitowski",
    "country": "United States Of America",
    "photo": "goldsarm/tony-kitowski.jpg",
    "gender": "male"
  },
  {
    "name": "Travis Bagent",
    "country": "United States Of America",
    "photo": "goldsarm/travis-bagent.jpg",
    "gender": "male"
  },
  {
    "name": "Vala Ichqiti",
    "country": "Georgia",
    "photo": "goldsarm/vala-ichqiti.jpg",
    "gender": "male"
  },
  {
    "name": "Valen Low",
    "country": "Singapore",
    "photo": "goldsarm/valen-low.png",
    "gender": "male"
  },
  {
    "name": "Valera Chubotaru",
    "country": "Russia",
    "photo": "goldsarm/valera-chubotaru.jpg",
    "gender": "male"
  },
  {
    "name": "Vasily Dautashvili",
    "country": "Georgia",
    "photo": "goldsarm/vaso-dautashvili.png",
    "gender": "male"
  },
  {
    "name": "Vitaly Laletin",
    "country": "Russia",
    "photo": "goldsarm/vitaly-laletin.png",
    "gender": "male"
  },
  {
    "name": "Vlad Dzisiak",
    "country": "Ukraine",
    "photo": "goldsarm/vlad-dzisiak.jpg",
    "gender": "male"
  },
  {
    "name": "Vladimir Maiorov",
    "country": "Russia",
    "photo": "goldsarm/vladimir-maiorov.jpg",
    "gender": "male"
  },
  {
    "name": "Vrezh Sedrakyan",
    "country": "Armenia",
    "photo": "goldsarm/sedrakyan-vrezh.jpg",
    "gender": "male"
  },
  {
    "name": "Wagner Bortalato",
    "country": "Brazil",
    "photo": "goldsarm/wagner-bortolato.jpg",
    "gender": "male"
  },
  {
    "name": "Wagner Bortolato",
    "country": "Brazil",
    "photo": "goldsarm/wagner-bortolato.jpg",
    "gender": "male"
  },
  {
    "name": "Wallace Dilley",
    "country": "United States Of America",
    "photo": "goldsarm/wallace-dilley.jpg",
    "gender": "male"
  },
  {
    "name": "Yerdaulet Sarybay",
    "country": "Kazakhstan",
    "photo": "goldsarm/yerdaulet-sarybay.jpg",
    "gender": "male"
  },
  {
    "name": "Yordan Tsonev",
    "country": "Bulgaria",
    "photo": "goldsarm/yordan-tsonev.jpg",
    "gender": "male"
  },
  {
    "name": "Yoshinobu Kanai",
    "country": "Japan",
    "photo": "goldsarm/yoshinobu-kanai.jpg",
    "gender": "male"
  },
  {
    "name": "Yusuf Yildizoglu",
    "country": "Turkey",
    "photo": "goldsarm/yusuf-ziya-yildizoglu.jpg",
    "gender": "male"
  },
  {
    "name": "Zaur Paizulaev",
    "country": "Russia",
    "photo": "goldsarm/zaur-paizulaev.png",
    "gender": "male"
  },
  {
    "name": "Zurab Tavberidze",
    "country": "Georgia",
    "photo": "goldsarm/zurab-tavbaridze.jpg",
    "gender": "male"
  },
  {
    "name": "Irakli Gamtenadze",
    "country": "Georgia",
    "photo": "goldsarm/irakli-gamtenadze.jpg",
    "gender": "male"
  }
];

export const athleteNames = [
  "Abdulmanaf Tuzuyev",
  "Adam Wawrzynski",
  "Ahmet Yenerer",
  "Aleksandr Beziazykov",
  "Aleksandra Ozerova",
  "Alex Kurdecha",
  "Alizhan Muratov",
  "Allen Ford",
  "Andrei Chipreanov",
  "Andrei Sharkevich",
  "Angie Rose",
  "Anna Gronlund",
  "Arif Ertem",
  "Arsen Khachatryan",
  "Artem Taranenko",
  "Artem Taynov",
  "Artur Makarov",
  "Artyom Morozov",
  "Auden Larratt",
  "Avtandil Tutberidze",
  "Ayane Takenaka",
  "Aymeric Pradines",
  "Azat Srapyan",
  "Bacho Saginashvili",
  "Barbora Bajciova",
  "Beket Aitbek",
  "Bela Plieva",
  "Betkili Oniani",
  "Bozhidar Simeonov",
  "Brad Grundy",
  "Brandon Allen",
  "Brandon Ellsessor",
  "Brian Shaw",
  "Brigitta Ivanfi",
  "Carolina Pettersson",
  "Chance Shaw",
  "Cobra Rhodes",
  "Cody Wood",
  "Corey Miller",
  "Corey West",
  "Craig Tullier",
  "Curtis Cameron",
  "Daniel Procopciuc",
  "Danil Ustinov",
  "Dave Chaffee",
  "David Dadikyan",
  "Davit Arabuli",
  "Davit Samushia",
  "Denis Cyplenkov",
  "Derek Smith",
  "Devon Larratt",
  "Dimitrina Petrova",
  "Doug Erlich",
  "Dustin Hyatt",
  "Eddie Hall",
  "Efe Komek",
  "Egle Vaitkute",
  "Ekaterina Nikisheva",
  "Elin Janeheim",
  "Elizabeth Mocek",
  "Emil Amirshadyan",
  "Engin Terzi",
  "Erkan Damar",
  "Ermes Gasparini",
  "Esra Kiraz",
  "Evgeny Prudnik",
  "Ferit Osmanli",
  "Fia Reisek",
  "Frank Lamparelli",
  "Gabor Botta Dukat",
  "Gabriela Vasconcelos",
  "Genadi Kvikvinia",
  "Georgi Tsvetkov",
  "Georgii Dzeranov",
  "Georgy Tautiev",
  "Haydar Gildil",
  "Herman Stevens",
  "Hristo Delidzhakov",
  "Hunter Noffz",
  "Ibragim Sagov",
  "Irakli Zirakashvili",
  "Irina Drieva",
  "Irina Gladkaya",
  "Ivan Matyushenko",
  "Ivan Portela",
  "Janis Amolins",
  "Jerry Cadorette",
  "Jocelyne Brisson",
  "John Brzenk",
  "John Therrien",
  "Jonathan Breda",
  "Joseph Meranto",
  "Joshua Grant",
  "Justin Bishop",
  "Kacper Sinica",
  "Kamil Jablonski",
  "Kevin Palko",
  "Khadzimurat Zoloev",
  "Khaled Jashell",
  "Kody Merritt",
  "Korean Hulk",
  "Krasimir Kostadinov",
  "Kydyrgali Ongarbaev",
  "Kyle Hutchison",
  "Lachlan Adair",
  "Larry Wheels",
  "Lars Rorbakken",
  "Leonidas Arkona",
  "Levan Saginashvili",
  "Maateiwarangi Heta-Morris",
  "Malin Bergstrom",
  "Marcio Barboza",
  "Matt Mask",
  "Mazahir Saidu",
  "Mehdi Abvolvand",
  "Michael Todd",
  "Mindaugas Tarasaitis",
  "Nedalin Hristov",
  "Nisa Camanan",
  "Nugo Chikadze",
  "Nugzari Chikadze",
  "Nurdalet Aidarkhan",
  "Oguzhan Kocak",
  "Oleg Cherkasov",
  "Oleg Petrenko",
  "Oleg Zhokh",
  "Olga Terpelova",
  "Omer Kozakoglu",
  "Paul Linn",
  "Paul Talbott",
  "Pavlo Derbedyenyev",
  "Petro Marharint",
  "Raimonds Liepins",
  "Ramzi Tayba",
  "Rebeka Martinkovicova",
  "Revaz Lutidze",
  "Riekerd Bornman",
  "Rino Masic",
  "Rob Vigeant Jr.",
  "Robbie Karstendiek",
  "Robbie Topie",
  "Robert Baxter",
  "Ron Bath",
  "Rosa Acosta (Boltadano)",
  "Ruslan Babaiev",
  "Rustam Babayev",
  "Ryan Belanger",
  "Ryan Bowen",
  "Sabin Badulescu",
  "Sahip Caglar",
  "Sandris Sedis",
  "Sarah Backman",
  "Sarah Collins",
  "Sasho Andreev",
  "Serhii Kalinichenko",
  "Stoyan Golemanov",
  "Talgat Aktaev",
  "Terence Opperman",
  "Thomas Manghi",
  "Tobias Sporrong",
  "Todd Hutchings",
  "Tom Holland",
  "Tom Rozits",
  "Toms Rozits",
  "Tony Kitowski",
  "Travis Bagent",
  "Vala Ichqiti",
  "Valen Low",
  "Valera Chubotaru",
  "Vasily Dautashvili",
  "Vitaly Laletin",
  "Vlad Dzisiak",
  "Vladimir Maiorov",
  "Vrezh Sedrakyan",
  "Wagner Bortalato",
  "Wagner Bortolato",
  "Wallace Dilley",
  "Yerdaulet Sarybay",
  "Yordan Tsonev",
  "Yoshinobu Kanai",
  "Yusuf Yildizoglu",
  "Zaur Paizulaev",
  "Zurab Tavberidze",
  "Irakli Gamtenadze"
];

export const countries = [
  "Armenia",
  "Australia",
  "Brazil",
  "Bulgaria",
  "Cameroon",
  "Canada",
  "Croatia",
  "Dominican Republic",
  "France",
  "Georgia",
  "Germany",
  "Hungary",
  "India",
  "Iran (Islamic Republic of)",
  "Italy",
  "Japan",
  "Kazakhstan",
  "Latvia",
  "Lithuania",
  "Moldova",
  "New Zealand",
  "Norway",
  "Poland",
  "Qatar",
  "Romania",
  "Russia",
  "Singapore",
  "Slovakia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sweden",
  "Turkey",
  "USA",
  "Ukraine",
  "United Kingdom",
  "United States",
  "United States Of America"
];
